"""Blueprint 8 — Full hybrid-optimizer SLURM workflow, run entirely locally.

This is the runnable companion to ``config/config_hybrid_workflow.yaml``: it
builds the same five-step per-iteration loop from scratch in a throwaway
scratch directory and then drives it through the *real* framework entry
points (``load_config`` + ``make_optimizer(...).run()`` — exactly what
``main.py --mode optimize --method de-nm`` does), so the config sample it is
based on is provably correct and not just aspirational documentation.

  Step 1 (stage):    ``case.source_dir`` (a tiny ``input.cfg`` with
                      ``@AMPLITUDE@``/``@DECAY@``/``@JOB_NAME@`` tokens, plus
                      ``simulate.py``) is copied into every case directory
                      and its tokens are substituted from that case's
                      parameter values.                            [case:]
  Step 2 (modify):    ``file_pipeline`` generates a ``params.json`` per case
                      from that case's ``amplitude``/``decay`` values.
                                                              [file_pipeline:]
  Step 3 (submit & wait): one fake-sbatch job per case is fired via
                      ``slurm.submit_cmd``; the hybrid DE→Nelder-Mead
                      optimizer submits a WHOLE generation of candidates
                      concurrently, then blocks once on
                      ``dispatcher.wait_for_batch`` for the batch.  [slurm:]
                      [optimizer: de_*]
  Step 4 (compare):   each case's ``output.dat`` curve is read and aligned
                      (cubic spline) onto ``experiment.csv``'s x-grid, then
                      scored with MSE via
                      :func:`~src.analysis.postprocess.curve_loss`.
                                                        [optimizer: postprocess]
  Step 5 (advance):   Differential Evolution mutates/selects the next
                      generation from the scored population; once it stalls
                      or exhausts its generation budget, Nelder-Mead
                      polishes the DE champion with the remaining budget.

No SLURM cluster is needed. ``slurm.submit_cmd`` below is a
``nohup bash run_script.sh & echo "Submitted batch job $!"`` one-liner: it
backgrounds the "job" and prints a fake id in exactly the
``Submitted batch job <N>`` shape ``SlurmDispatcher._extract_job_id`` already
parses for real sbatch output. Neither ``squeue`` nor ``sacct`` exist on a
laptop, so ``SlurmDispatcher.job_state()``'s documented fallback kicks in —
queue-absence (here: command-not-found) is treated as ``COMPLETED`` — and it
is the framework's own file-existence polling
(``ResultParser.wait_for_output`` / ``curve_loss``'s missing-file handling)
that actually gates each evaluation on the simulation having produced real
output. For that gate to be meaningful, ``scan.output_file`` MUST be the
file the simulation itself writes (``output.dat``) and not a redirected log
(see the comment on the ``scan:`` block below). ``simulate.py`` is
deliberately stdlib-only (no numpy) so it starts fast and the whole demo
finishes in well under a minute.

Run: ``python examples/example_08_hybrid_slurm_workflow.py``
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
import pandas as pd
import yaml

from varify.src.analysis.plotting import PlotSuite  # noqa: E402
from varify.src.common.config import load_config  # noqa: E402
from varify.src.optimizer import make_optimizer  # noqa: E402

TRUE_AMPLITUDE = 2.5
TRUE_DECAY = 0.7

# ── Static file contents written into the scratch area ─────────────────────

SIMULATE_PY = '''"""Tiny stand-in "simulation": reads input.cfg + params.json, writes output.dat.

Deliberately stdlib-only (no numpy import) so the process starts fast under
the local fake-sbatch trick used by the parent example -- the framework's
completion polling has no real scheduler to defer to on a laptop, so a
lightweight job script keeps the race with SlurmDispatcher's job_state()
fallback comfortably in our favor.
"""
import json
import math
from pathlib import Path

params = json.loads(Path("params.json").read_text(encoding="utf-8"))
amplitude = float(params["amplitude"])
decay = float(params["decay"])

# input.cfg was staged + @TOKEN@-substituted by case.source_dir (Step 1);
# params.json was generated by file_pipeline (Step 2). Read both to prove
# each mechanism actually reached this case directory.
job_name = "unknown"
cfg_path = Path("input.cfg")
if cfg_path.exists():
    for line in cfg_path.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith("job_name"):
            job_name = line.split("=", 1)[1].strip()

n = 40
xs = [i * (10.0 / (n - 1)) for i in range(n)]
ys = [amplitude * math.exp(-decay * x) * math.sin(2 * math.pi * x) for x in xs]

with open("output.dat", "w", encoding="utf-8") as fh:
    fh.write(f"# simulate.py output for {job_name}\\n")
    for x, y in zip(xs, ys):
        fh.write(f"{x:.6f} {y:.6f}\\n")
'''

INPUT_CFG_TEMPLATE = """# per-case input configuration (staged by case.source_dir, Step 1;
# @TOKEN@ substitution applied in place since this file matches
# case.substitute_globs).
job_name = @JOB_NAME@
amplitude = @AMPLITUDE@
decay = @DECAY@
"""

RUN_SCRIPT_TEMPLATE = """#!/bin/bash
# Rendered per-case from templates/run_script.sh.template (Step 1, after
# source_dir staging). On a real cluster this would carry #SBATCH
# directives; here it is just executed directly by the fake-sbatch
# one-liner in slurm.submit_cmd below.
# Job: @JOB_NAME@
python3 simulate.py
"""


def _damped_sine(x: np.ndarray, amplitude: float, decay: float) -> np.ndarray:
    return amplitude * np.exp(-decay * x) * np.sin(2.0 * np.pi * x)


def _write_xy(path: Path, x: np.ndarray, y: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# x,y\n")
        for xi, yi in zip(x, y):
            fh.write(f"{xi:.6f},{yi:.6f}\n")


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    run_dir = repo_root / "results" / f"example_08_{stamp}"

    source_dir = run_dir / "source_dir"
    templates_dir = run_dir / "templates"
    sweep_root = run_dir / "sweep_workspace"
    plots_dir = run_dir / "plots"
    source_dir.mkdir(parents=True, exist_ok=True)
    templates_dir.mkdir(parents=True, exist_ok=True)

    # ── Step 1 inputs: files staged verbatim / @TOKEN@-substituted per case. ──
    (source_dir / "input.cfg").write_text(INPUT_CFG_TEMPLATE, encoding="utf-8")
    (source_dir / "simulate.py").write_text(SIMULATE_PY, encoding="utf-8")
    (templates_dir / "run_script.sh.template").write_text(
        RUN_SCRIPT_TEMPLATE, encoding="utf-8"
    )

    # ── Synthetic "experiment": true amplitude/decay + noise, ~120 points. ────
    rng = np.random.default_rng(2026)
    x_exp = np.linspace(0.0, 10.0, 120)
    y_exp = _damped_sine(x_exp, TRUE_AMPLITUDE, TRUE_DECAY) + rng.normal(
        scale=0.05, size=x_exp.size
    )
    experimental_path = run_dir / "experiment.csv"
    _write_xy(experimental_path, x_exp, y_exp)

    # ── Config YAML wiring the whole workflow together (Steps 1-5). ───────────
    # All paths are absolute so the optimizer can run from any cwd with no
    # chdir (case_dir / sweep_root / experimental_data / template_files /
    # history_csv / plots_dir are all resolved as-given, never joined
    # against sweep_root -- see src/common/config.py's load_config).
    cfg_dict = {
        "hooks_module": str(repo_root / "config" / "hooks.py"),

        # Step 1 (workspace root) + legacy scan settings (mode is unused by
        # de-nm but load_config requires a valid value).
        # CRUCIAL: output_file must be the file the simulation itself writes
        # (output.dat, same as optimizer.sim_output_file), NOT a redirected
        # log like stdout.log. The shell redirection in slurm.submit_cmd
        # creates stdout.log the instant the job is *submitted*, so polling
        # it would declare each job "done" before simulate.py has written
        # any results -- ResultParser.wait_for_output (which gates the
        # sequential Nelder-Mead phase between evaluations) polls exactly
        # this file for existence.
        "scan": {
            "mode": "grid",
            "workspace": str(sweep_root),
            "template_files": [str(templates_dir / "run_script.sh.template")],
            "output_file": "output.dat",
            "results_csv": str(run_dir / "sweep_results.csv"),
            "submission_log": str(run_dir / "submission.log"),
        },

        # Step 1: stage source_dir into every case dir, @TOKEN@-substitute
        # only the files matching substitute_globs (input.cfg here).
        "case": {
            "source_dir": str(source_dir),
            "substitute_globs": ["*.cfg"],
        },

        # Search space: damped-oscillator amplitude/decay, both with MCMC
        # prior bounds (the hybrid optimizer's DE search box).
        "parameters": [
            {
                "name": "amplitude",
                "default": 2.0,
                "mcmc": {
                    "prior_low": 0.1, "prior_high": 5.0,
                    "init_center": 2.0, "init_width": 0.5,
                },
            },
            {
                "name": "decay",
                "default": 0.5,
                "mcmc": {
                    "prior_low": 0.01, "prior_high": 2.0,
                    "init_center": 0.5, "init_width": 0.2,
                },
            },
        ],

        # Step 3: submit + wait. See the module docstring for why this
        # nohup/echo one-liner is a safe stand-in for a real `sbatch` on a
        # machine with no scheduler at all. NOTE: leave slurm.directives
        # empty here -- SlurmSettings.effective_submit_cmd would otherwise
        # splice "--key=value" tokens into the middle of this one-liner.
        "slurm": {
            "submit_cmd": (
                "bash -c 'nohup bash run_script.sh > stdout.log 2>&1 & "
                "echo Submitted batch job $!'"
            ),
        },

        # Steps 3-5: hybrid DE -> Nelder-Mead, scored by postprocess (Step 4).
        "optimizer": {
            "method": "de-nm",
            "maximize": False,
            "max_evaluations": 60,
            "tolerance": 1.0e-4,
            "poll_interval": 1.0,
            "job_timeout": 120.0,
            "history_csv": str(run_dir / "optimization_history.csv"),
            "postprocess": True,
            "experimental_data": str(experimental_path),
            "sim_output_file": "output.dat",
            "spline_k": 3,
            "spline_s": 0.0,
            "loss": "mse",
            "interp": "spline",
            "de_popsize": 8,
            "de_generations": 6,
            "de_f": 0.7,
            "de_cr": 0.9,
            "de_stall_generations": 5,
            "de_seed": 7,
        },

        "analysis": {
            "plots_dir": str(plots_dir),
            "sqlite_db": str(run_dir / "results.db"),
        },

        # Step 2: generate params.json per case from that case's own
        # amplitude/decay values ("$name" resolves against the case params).
        "file_pipeline": [
            {
                "action": "generate",
                "file": "params.json",
                "fmt": "json",
                "keys": {"amplitude": "$amplitude", "decay": "$decay"},
            },
        ],
    }

    config_path = run_dir / "config_generated.yaml"
    config_path.write_text(yaml.safe_dump(cfg_dict, sort_keys=False), encoding="utf-8")

    print(f"Scratch area       -> {run_dir}")
    print(f"Config             -> {config_path}")
    print(
        f"Experimental data  -> {experimental_path}  "
        f"(TRUE amplitude={TRUE_AMPLITUDE}, decay={TRUE_DECAY})"
    )
    print()

    # ── Steps 1-5: load the config exactly like `main.py --mode optimize` ────
    # would, and run the hybrid optimizer for real.
    cfg = load_config(config_path)
    optimizer = make_optimizer(cfg, "de-nm")
    optimizer.run()

    # ── Recovered vs. true parameters. ─────────────────────────────────────
    # Picked from the best (lowest-loss) row across the *entire* history
    # (DE and NM phases together) rather than trusting the optimizer's own
    # "final" point -- robust to the rare NaN/penalty eval this local
    # fallback path can produce if a job script is unusually slow to start
    # (see the module docstring); a handful of penalized candidates simply
    # never win the argmin below.
    history = pd.read_csv(cfg.optimizer.history_csv)
    finite = history[np.isfinite(history["objective"])]
    if finite.empty:
        print("No finite evaluations recovered -- see the optimizer log above.")
        sys.exit(1)
    best_row = finite.loc[finite["objective"].idxmin()]
    best_amplitude = float(best_row["amplitude"])
    best_decay = float(best_row["decay"])
    best_case_dir = Path(best_row["case_dir"])

    amp_err = abs(best_amplitude - TRUE_AMPLITUDE) / TRUE_AMPLITUDE
    decay_err = abs(best_decay - TRUE_DECAY) / TRUE_DECAY

    print()
    print("Recovered vs. true parameters:")
    print(
        f"  amplitude: recovered={best_amplitude:.4f}  true={TRUE_AMPLITUDE}  "
        f"error={amp_err:.1%}"
    )
    print(
        f"  decay:     recovered={best_decay:.4f}  true={TRUE_DECAY}  "
        f"error={decay_err:.1%}"
    )
    print(f"  loss (mse): {best_row['objective']:.6g}")
    print(f"  best case_dir: {best_case_dir}")
    print(f"  evaluations:   {len(history)}")

    # ── Step 4 recap: overlay the best simulated curve against experiment. ───
    plotter = PlotSuite(cfg)
    plotter.plot_overlay(
        best_case_dir, cfg.optimizer.experimental_data, cfg.optimizer.sim_output_file,
        name="overlay_best",
    )

    print()
    print(f"History CSV  -> {cfg.optimizer.history_csv}")
    print(f"Overlay PNG  -> {cfg.analysis.plots_dir / 'overlay_best.png'}")
    print(f"Sweep root   -> {sweep_root}")

    if amp_err > 0.20 or decay_err > 0.20:
        print(
            "\nWARNING: recovered parameters are outside the +/-20% "
            "tolerance band."
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
